### ISSUE TITLE
Implementing pythonic-api project

### ISSUE THREAD

**Issue by Marlysson** [gaojiuli/xweb#3]
Firstly , great project.

I've saw your methods in some classes and saw that you use getters in java-like , what you think about use a pythonic way of this:

Instead:

```python
class Response:
    ....
    def get_headers(self):
        return dict()
```

and to use so : 

```python
a = Response()
print(a.get_headers())
```

To do 

```python
class Response:
    ....
    @property
    def headers(self):
        return dict()
```

and to use:

```python
a = Response()
print(a.headers)
```

**Comment by elliotgao2** [comment]
Thanks and I will update them later
