### ISSUE TITLE
auto-reload

### ISSUE THREAD

**Issue by elliotgao2** [gaojiuli/xweb#4]
I think this is a important function for developing.
After we code and save, this develop server should auto-reload.

**Comment by shershen08** [comment]
I've created a sample reloading implementation here - https://gist.github.com/shershen08/b54950d5904699187347374a07b96d5f
Let me know what you think

**Comment by elliotgao2** [comment]
When we use Django. Once we save a file , the server auto reload. I want the function in Django. But I want to find a way to realize this.
